##########################################################
######### START - ResourceManager Monitor  ###############
##########################################################
resourceManagerMonitor:
  enabled: true
  metricPrefix: "Custom Metrics|HadoopMonitor|ResourceManager"
  #metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|HadoopMonitor|ResourceManager"
  servers:
    - uri: "http://192.168.1.216:8088"
      #username: "admin"
      #password: "admin"
      #name: "" #Required only if there are multiple servers

  # This will monitor the type of applications in the monitoringTimePeriod
  # Only the aggregate of State and Finished Status will be reported
  applications:
    - type: "MAPREDUCE"
      names: [".*"]
  #In Minutes
  monitoringTimePeriod: 15

  numberOfThreads: 1
  connection:
    socketTimeout: 5000
    connectTimeout: 2500
    sslCertCheckEnabled: false
    sslVerifyHostname: false
  #Run it as a scheduled task instead of running every minute.
  #If you want to run this every minute, comment this out
  #taskSchedule:
    #numberOfThreads: 1
    #taskDelaySeconds: 120

  #Password Encryption Support.
  #encryptionKey: welcome
##########################################################
######### END - ResourceManager Monitor  ###############
##########################################################


##########################################################
######### START - AMBARI MONITOR  ########################
##########################################################
ambariMonitor:
  enabled: true
  metricPrefix: "Custom Metrics|HadoopMonitor|Ambari"
  #metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|HadoopMonitor|Ambari"
  servers:
    - uri: "http://192.168.1.218:8080/api/v1"
      username: "admin"
      password: "admin"
      #name: "" #Required only if there are multiple servers

  # Regex expressions are supported in the filters
  filters:
    clusters:
      includes: ['.*']
    hosts:
      includes: ['.*']
    services:
      includes: ['.*']

  numberOfThreads: 1
  connection:
    socketTimeout: 10000
    connectTimeout: 2500
    sslCertCheckEnabled: false
    sslVerifyHostname: false
  #Run it as a scheduled task instead of running every minute.
  #If you want to run this every minute, comment this out
  #taskSchedule:
    #numberOfThreads: 1
    #taskDelaySeconds: 120

  #Password Encryption Support.
  #encryptionKey: welcome

##########################################################
######### END - AMBARI MONITOR  ##########################
##########################################################